# Copy and paste everything below (not including) the --- into the
# "controllers" section of your reactor.yaml file.
---

  - id: openai
    name: OpenAI
    implementation: OpenAIController
    enabled: true
    config:
      models:
        - id: openai
          name: OpenAI GPT-4
          model: gpt-4
          service: openai
          api_key: xxxxx # taken from your OpenAI dashboard
          max_tokens: 2000 # default
          temperature: 0.5 # default
          top_p: 1 # default
          frequency_penalty: 0 # default
          presence_penalty: 0 # default
          stop: null # default
        - id: azure
          name: Azure GPT-4o
          model: gpt-4o
          service: azure
          endpoint: "https://XXX.openai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2023-03-15-preview" # taken from your Azure GPT-4 service
          api_key: xxxx # taken from Azure
          max_tokens: 2000 # default
          temperature: "0.5" # default
          top_p: 1 # default
          frequency_penalty: 0 # default
          presence_penalty: 0 # default
          stop: null # default